### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by ShadwMan** [letienne/teslamate-abrp#1]
I just requested and received an API key. It appears that the guy managing the API keys is requesting that the API key is integrated into the solution instead of individuals request keys. 

Do you want his contact information so that this might be integrated into the solution?

**Comment by fetzu** [comment]
Just thought I'd leave this here: I discussed this with Bo and received an API key we should all use (d49234a5-2553-454e-8321-3fe30b49aa64) and integrated directly in [the fork of the fork of the fork](https://github.com/fetzu/teslamate-abrp/) with some doc and an useable docker image.

**Comment by letienne** [comment]
thanks again
