### ISSUE TITLE
Adding LICENSE

### ISSUE THREAD

**Issue by fetzu** [letienne/teslamate-abrp#2]
Hello there @letienne,

As your code is the basis for quite a few forks (for which we now have [an easily setup-able implementation](https://github.com/fetzu/teslamate-abrp/); I'd like to know if you wouldn't mind adding a LICENSE file to this repo? That way I could go down the chain and also license the implementation properly. Might I suggest the MIT license in this case (it would also match TeslaMate's).

Thanks for everything.

Cheers,
fetzu

**Comment by letienne** [comment]
thanks for the suggestion and following up on my quick and dirty python file...
happy to see that others might use it :)
